//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wunion.DataAdapter.NetCore.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wunion.DataAdapter.NetCore.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // About.js
        ///var About = new Object();
        ///About.CurrentDataBase = &quot;Default&quot;;
        ///About.CurrentPage = 1;
        ///About.PageSize = 10;
        ///
        ///// 初始化。
        ///About.Initialize = function () {
        ///    $(&quot;.navbar&quot;).find(&quot;a&quot;).each(function () {
        ///        $(this).on(&quot;click&quot;, function () {
        ///            About.ToolbarItemClick(this);
        ///        });
        ///    });
        ///    $(&quot;#select-group&quot;).on(&quot;change&quot;, function () {
        ///        About.GetGroupData($(&quot;#select-group&quot;).val());
        ///    });
        ///
        ///    About.GetAllGroup();
        ///};
        ///
        ///// 工具栏点击事件处理
        ///About.ToolbarItemClick = fu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 显示添加分组对话框。
        ///About.ShowAddGroup = function () {
        ///    $(&quot;#dialog-title&quot;).html(&quot;添加分组&quot;);
        ///    $(&quot;#dialog-content&quot;).html(&apos;&lt;div class=&quot;row&quot;&gt;&lt;div class=&quot;col-xs-8 col-sm-6&quot; style=&quot;width: auto; padding-top: 6px&quot;&gt;组名称：&lt;/div&gt;&apos; +
        ///        &apos;&lt;div class=&quot;col-xs-4 col-sm-6&quot; style=&quot;width: auto;&quot;&gt;&lt;input id=&quot;GrpName&quot; type=&quot;text&quot; class=&quot;form-control&quot; style=&quot;width: 235px&quot; /&gt;&lt;/div&gt;&lt;/div&gt;&apos;);
        ///
        ///    var $myModal = $(&quot;#modalDialog&quot;);
        ///    $myModal.find(&quot;.modal-dialog&quot;).css(&quot;width&quot;, &quot;360px&quot;);
        ///    $myModal.find(&quot;#modalbtn-ok&quot;).unb [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string About_Change {
            get {
                return ResourceManager.GetString("About_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        /// * @author zhixin wen &lt;wenzhixin2010@gmail.com&gt;
        /// * version: 1.11.1
        /// * https://github.com/wenzhixin/bootstrap-table/
        /// */
        ///
        ///(function ($) {
        ///    &apos;use strict&apos;;
        ///
        ///    // TOOLS DEFINITION
        ///    // ======================
        ///
        ///    var cachedWidth = null;
        ///
        ///    // it only does &apos;%s&apos;, and return &apos;&apos; when arguments are undefined
        ///    var sprintf = function (str) {
        ///        var args = arguments,
        ///            flag = true,
        ///            i = 1;
        ///
        ///        str = str.replace(/%s/g, function () {
        ///            var arg = args[i++];
        ///
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bootstrap_table {
            get {
                return ResourceManager.GetString("bootstrap_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        /// * @author zhixin wen &lt;wenzhixin2010@gmail.com&gt;
        /// * version: 1.11.1
        /// * https://github.com/wenzhixin/bootstrap-table/
        /// */
        ///
        ///.bootstrap-table .table {
        ///    margin-bottom: 0 !important;
        ///    border-bottom: 1px solid #dddddd;
        ///    border-collapse: collapse !important;
        ///    border-radius: 1px;
        ///}
        ///
        ///    .bootstrap-table .table:not(.table-condensed),
        ///    .bootstrap-table .table:not(.table-condensed) &gt; tbody &gt; tr &gt; th,
        ///    .bootstrap-table .table:not(.table-condensed) &gt; tfoot &gt; tr &gt; th,
        ///    .bootstrap-t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bootstrap_table_css {
            get {
                return ResourceManager.GetString("bootstrap_table_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        /// * Bootstrap Table Chinese translation
        /// * Author: Zhixin Wen&lt;wenzhixin2010@gmail.com&gt;
        /// */
        ///(function ($) {
        ///    &apos;use strict&apos;;
        ///
        ///    $.fn.bootstrapTable.locales[&apos;zh-CN&apos;] = {
        ///        formatLoadingMessage: function () {
        ///            return &apos;正在努力地加载数据中，请稍候……&apos;;
        ///        },
        ///        formatRecordsPerPage: function (pageNumber) {
        ///            return &apos;每页显示 &apos; + pageNumber + &apos; 条记录&apos;;
        ///        },
        ///        formatShowingRows: function (pageFrom, pageTo, totalRows) {
        ///            return &apos;显示第 &apos; + pageFrom + &apos; 到第 &apos; + pageTo + &apos; 条记 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string bootstrap_table_zh_CN {
            get {
                return ResourceManager.GetString("bootstrap_table_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///CryptoJS v3.1.2
        ///code.google.com/p/crypto-js
        ///(c) 2009-2013 by Jeff Mott. All rights reserved.
        ///code.google.com/p/crypto-js/wiki/License
        ///*/
        ///var CryptoJS=CryptoJS||function(h,r){var k={},l=k.lib={},n=function(){},f=l.Base={extend:function(a){n.prototype=this;var b=new n;a&amp;&amp;b.mixIn(a);b.hasOwnProperty(&quot;init&quot;)||(b.init=function(){b.$super.init.apply(this,arguments)});b.init.prototype=b;b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:func [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CryptoJS_core_min {
            get {
                return ResourceManager.GetString("CryptoJS_core_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///CryptoJS v3.1.2
        ///code.google.com/p/crypto-js
        ///(c) 2009-2013 by Jeff Mott. All rights reserved.
        ///code.google.com/p/crypto-js/wiki/License
        ///*/
        ///(function(){var h=CryptoJS,j=h.lib.WordArray;h.enc.Base64={stringify:function(b){var e=b.words,f=b.sigBytes,c=this._map;b.clamp();b=[];for(var a=0;a&lt;f;a+=3)for(var d=(e[a&gt;&gt;&gt;2]&gt;&gt;&gt;24-8*(a%4)&amp;255)&lt;&lt;16|(e[a+1&gt;&gt;&gt;2]&gt;&gt;&gt;24-8*((a+1)%4)&amp;255)&lt;&lt;8|e[a+2&gt;&gt;&gt;2]&gt;&gt;&gt;24-8*((a+2)%4)&amp;255,g=0;4&gt;g&amp;&amp;a+0.75*g&lt;f;g++)b.push(c.charAt(d&gt;&gt;&gt;6*(3-g)&amp;63));if(e=c.charAt(64))for(;b.length%4;)b.push(e);ret [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string enc_base64_min {
            get {
                return ResourceManager.GetString("enc_base64_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*!
        /// DataTables 1.10.12
        /// ©2008-2015 SpryMedia Ltd - datatables.net/license
        ///*/
        ///(function(h){&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],function(D){return h(D,window,document)}):&quot;object&quot;===typeof exports?module.exports=function(D,I){D||(D=window);I||(I=&quot;undefined&quot;!==typeof window?require(&quot;jquery&quot;):require(&quot;jquery&quot;)(D));return h(I,D,D.document)}:h(jQuery,window,document)})(function(h,D,I,k){function X(a){var b,c,d={};h.each(a,function(e){if((b=e.match(/^([^A-Z]+?)([A-Z])/))&amp;&amp;-1!==&quot;a aa ai ao as b [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jquery_dataTables_min {
            get {
                return ResourceManager.GetString("jquery_dataTables_min", resourceCulture);
            }
        }
    }
}
