//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wunion.DataAdapter.EntityGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wunion.DataAdapter.EntityGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] CodeBuilder {
            get {
                object obj = ResourceManager.GetObject("CodeBuilder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;strings&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;region-name&quot; value=&quot;English (United States)&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;MainForm&quot; value=&quot;Wunion DataAdapter EntityUtils Coder&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;CaptionTitle&quot; value=&quot;CodeGenerator&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;CopyrightText&quot; value=&quot;Copyright (C) cnzhnet all rights reserved.&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;ToolDescription&quot; value=&quot;If you did not set the comments for a table or field when you designed th [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///	t1.TABLE_NAME AS tableName,
        ///	t1.COLUMN_NAME AS paramName,
        ///	CASE ISNULL(t1.COLUMN_COMMENT) WHEN TRUE THEN &apos;&apos; ELSE t1.COLUMN_COMMENT END paramDescription, 
        ///	t1.DATA_TYPE AS dbType, 
        ///	CASE t1.COLUMN_DEFAULT WHEN &apos;NULL&apos; THEN NULL ELSE t1.COLUMN_DEFAULT END defaultValue,  
        ///	CASE t1.IS_NULLABLE WHEN &apos;NO&apos; THEN 0 ELSE 1 END allowNull, 
        ///	CASE t1.COLUMN_KEY WHEN &apos;PRI&apos; THEN 1 ELSE 0 END isPrimary,
        ///	CASE t1.EXTRA WHEN &apos;auto_increment&apos; THEN 1 ELSE 0 END isIdentity
        ///FROM
        ///	INFORMATION_SCHEMA.COLUMNS t1 
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MySQLDbSchema {
            get {
                return ResourceManager.GetString("MySQLDbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///	cols.table_name as tableName, 
        ///	cols.column_name as paramName, 
        ///	case cols.is_nullable when &apos;YES&apos; then true else false end allowNull, 
        ///	cols.data_type, 
        ///	cols.udt_name as dbType,
        ///	case pkt.constraint_type when &apos;PRIMARY KEY&apos; then true else false end isPrimary,
        ///	case when position(&apos;nextval(&apos; in cols.column_default) &gt; 0 then true else false end isIdentity 
        ///from 
        ///	information_schema.columns cols 
        ///	left join (select tc.constraint_type,tc.table_name,tc.constraint_name,ccu.column_name from infor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PostgreSQLDbSchema {
            get {
                return ResourceManager.GetString("PostgreSQLDbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SQLite3DbSchema {
            get {
                return ResourceManager.GetString("SQLite3DbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///    tableName= d.[name],
        ///    tableDescription=f.[value],
        ///    tabletype=d.xtype,
        ///    paramOrder= a.colorder,
        ///    paramName= a.[name],
        ///    isIdentity= COLUMNPROPERTY( a.id,a.name 
        ///
        ///,&apos;IsIdentity&apos;),
        ///    isPrimary=case when exists(SELECT 1 FROM sysobjects where xtype=&apos;PK&apos; and parent_obj=a.id and name in (
        ///                     SELECT name FROM sysindexes WHERE indid in(SELECT indid FROM sysindexkeys WHERE id = a.id AND 
        ///					 colid=a.colid))) then 1 else 0 end,
        ///    dbType= b.[name],
        ///    dataS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQLServerDbSchema {
            get {
                return ResourceManager.GetString("SQLServerDbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] WriteCode {
            get {
                object obj = ResourceManager.GetObject("WriteCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;strings&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;region-name&quot; value=&quot;简体中文（中国）&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;MainForm&quot; value=&quot;Wunion DataAdapter EntityUtils 代码生成工具&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;CaptionTitle&quot; value=&quot;代码生成器&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;CopyrightText&quot; value=&quot;Copyright (C) 巽翎君保留所有权利.&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;ToolDescription&quot; value=&quot;若在设计数据库时没有为表或字段设置备注信息，可以在“注释”一列为生成的代码添加注释信息，同时还可根据需要保存或加载它们.&quot; /&gt;
        ///  &lt;string bind-ui=&quot;true&quot; key=&quot;GroupBoxOptions&quot; v [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
